//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminFile()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int AdminFileID { get; set; }
        public int GenderID { get; set; }
        public Nullable<int> SSN { get; set; }
        public int TitleId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
